### ISSUE TITLE
KuLGaP online tool data visualisation discrepancy

### ISSUE THREAD

**Issue by GillMundin** [bhklab/KuLGaP#2]
Using the example dataset provided with the online analysis tool, there is a discrepancy with how the data are plotted.  It appears to be to do with whether the dataset for each individual is truncated before the maximum timepoint or not.  See the attached file which compares the example data plotted in Excel with the graph generated by the online tool.

Please could you investigate to see whether this anomaly relates just to the data visualisation, or also to the statistical analysis?  

Kind regards, 
Gill Mundin

![KuLGaP plots vs Excel plots](https://user-images.githubusercontent.com/51286369/143548476-39fab901-c804-4ed0-a3c9-10ccd38d9c98.png)
.

**Comment by gangeshberi** [comment]
Hi @GillMundin,

Thank you for finding the oddity and opening a GitHub issue. I am almost certain it's due to the truncation that we are doing based on certain rules in our code base. But, I will investigate it, and hopefully by the end of the day Monday it will be fixed and the changes will be live. 

Best,
Gangesh Beri

**Comment by gangeshberi** [comment]
Hi @GillMundin 

The issue was due to an error in the function that prepares the data for the growth curve, I have fixed the issue and made the changes live. Also, for the average curves, the values are cut off if there is only a single curve (availability of the data for the curve) being plotted after the cut-off point. 

I have also verified both the test curves provided on the website using the R code. 

![test1](https://user-images.githubusercontent.com/41119826/144769972-f2fec72d-5591-4333-a814-b9831ee89cca.png)

![test2](https://user-images.githubusercontent.com/41119826/144769975-2d9c30c7-8867-4a03-9b50-025787692849.png)

Thank you again for pointing out the issue, please let me know in case you encounter any other issues.

Best,
Gangesh Beri

**Comment by gangeshberi** [comment]
@bhaibeka For your reference.

**Comment by gangeshberi** [comment]
Hey @GillMundin,

I am closing the issue, if you have any issues in the future please feel free to create a new issue or re-open this issue if it's related to this one.

Best,
Gangesh Beri

**Comment by GillMundin** [comment]
Hi Gangesh,

Thanks for your assistance in fixing the problem

Best wishes

Gill
